services:
  slab-ht2000:
    build: .
    image: slab-ht2000:latest
    container_name: slab_ht2000
    restart: unless-stopped
    
    
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./config.yaml:/app/config.yaml:ro
    
    environment:
      - PYTHONUNBUFFERED=1
